language: csharp
mono: none
dotnet: 5.0.102
solution: Dawn of Light.sln
sudo: false # Use container-based infrastructure

env:
  matrix:
   - BUILD_TARGET=Debug
   - BUILD_TARGET=Release

script:
 - dotnet build --configuration=$BUILD_TARGET
 - dotnet add Tests package NUnit.ConsoleRunner --version 3.11.1 --package-directory test
 - ./test/nunit.consolerunner/*/tools/nunit3-console.exe ./build/Tests/$BUILD_TARGET/lib/Tests.dll --where "namespace =~ 'DOL.UnitTests' and category!='Explicit'"
 - ./test/nunit.consolerunner/*/tools/nunit3-console.exe ./build/Tests/$BUILD_TARGET/lib/Tests.dll --where "namespace =~ 'DOL.Integration' and category!='Explicit'"
