language: csharp
mono: none
dotnet: 5.0.102
solution: Dawn of Light.sln
sudo: false # Use container-based infrastructure

env:
  matrix:
   - BUILD_TARGET=Debug
   - BUILD_TARGET=Release

script:
 - dotnet build --configuration=$BUILD_TARGET
 - dotnet test build/Tests/$BUILD_TARGET/lib/Tests.dll --filter "FullyQualifiedName~DOL.UnitTests & TestCategory!=Explicit"
 - dotnet test build/Tests/$BUILD_TARGET/lib/Tests.dll --filter "FullyQualifiedName~DOL.Integration & TestCategory!=Explicit"
