name: CI Net Framework

on:
  push:
    branches: [ CI ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        buildtarget: [Debug]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install p7zip tree
          echo "Hello release" > testfile
          7z a -tzip test.zip testfile
          7z a -tzip test2.zip testfile
          git fetch --tags -q
          CURRENTTAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$" | tail -n1)
          export NEXTTAG=$(echo $CURRENTTAG | cut -d'.' -f1-3).$(($(echo $CURRENTTAG | cut -d'.' -f4)+1)) #increment by one
          
          echo "nexttag=$NEXTTAG" >> $GITHUB_ENV
          
          echo ${{ env.nexttag }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.nexttag }}
          title: "Development Build"
          files: |
            *.zip
          
