name: CI Net Framework

on:
  push:
    branches: [ CI ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        buildtarget: [Debug]
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install p7zip
          echo "Hello release" > testfile
          7z a -tzip test.zip testfile
          7z a -tzip test2.zip testfile
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.9.7.*"
          title: "Development Build"
          files: |
            *.zip
          
