name: CI Net Framework

on:
  push:
    branches: [ CI ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        buildtarget: [Debug]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install p7zip tree
          echo "Hello release" > testfile
          7z a -tzip test.zip testfile
          7z a -tzip test2.zip testfile
          git fetch --tags -q
          CURRENTTAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$" | tail -n1)
          echo $CURRENTTAG
          export NEXTTAG=$(echo $CURRENTTAG | cut -d'.' -f1-3).$(($(echo $CURRENTTAG | cut -d'.' -f4)+1)) #increment by one
          echo $NEXTTAG
          
          echo "::set-env name=NEXTTAG::$NEXTTAG"
          
          echo ${{ env.NEXTTAG }}
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: ${{ env.NEXTTAG }}
#          title: "Development Build"
#          files: |
#            *.zip
      - name: Get Info
        run: echo ${{ env.NEXT_TAG }}
          
