name: CI Net Framework

on:
  push:
    branches: [ CI ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        buildtarget: [Debug]
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install p7zip
          echo "Hello release" > testfile
          7z a -tzip test-${{ matrix.buildtarget }}.zip testfile
      - uses: actions/upload-artifact@v2
        with:
          name: test.zip
          path: test-{{ matrix.buildtarget }}.zip
          if-no-files-found: error
          
