name: CI Net Framework

on:
  push:
    branches: [ CI ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        buildtarget: [Debug]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          DEBIAN_FRONTEND=noninteractive apt install mono-complete nuget -y

      - name: Build
        run: |
             Configuration=${{ matrix.buildtarget }} nuget restore
             nuget install NUnit.Console -Version 3.11.1 -OutputDirectory test -ExcludeVersion

      - name: Test
        run: |
             MONO_IOMAP=case msbuild /p:Configuration=${{ matrix.buildtarget }} "Dawn of Light.sln"
             LANG=en_US.CP1252 mono ./test/NUnit.ConsoleRunner/tools/nunit3-console.exe ./build/Tests/${{ matrix.buildtarget }}/lib/Tests.dll --where "namespace =~ 'DOL.UnitTests' and category!='Explicit'"
             LANG=en_US.CP1252 mono ./test/NUnit.ConsoleRunner/tools/nunit3-console.exe ./build/Tests/${{ matrix.buildtarget }}/lib/Tests.dll --where "namespace =~ 'DOL.Integration' and category!='Explicit'"
