name: Tests on NetCore/Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test_netcore_windows:
    name: NetCore Tests on Windows
    strategy:
      matrix:
        build_target: [Debug]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 #v5.3.0
        with:
          dotnet-version: '10.0.x'
      - name: Build
        run: |
          dotnet build -c ${{ matrix.build_target }} "Tests\Tests.csproj" --verbosity normal
      - name: Test
        run: |
          dotnet test .\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.UnitTests"
          dotnet test .\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.Integration"
